### ISSUE TITLE
Gzip test coverage and configuration

### ISSUE THREAD

**Issue by Ziinc** [supabase/plug_caisson#4]
- [ ] Port over max chunk tests from logflare
- [ ] Allow max chunk number to be configurable via `Application.get_env/3`
cc @hauleth

**Comment by hauleth** [comment]
I have different idea for limiting amount of chunks read. Namely we should use `:length` option passed tot the `PlugCaisson.read_body/2` function, that will extract about `:length` bytes from the body, and then return `{:more, data, conn}` if it will hit that limit. We probably also should prevent subsequent reads from `Plug.Conn.read_body/2` if we have hit that limit, but for now the idea is simple - return to user about `:length` bytes (as it is provided by `Plug.Conn.read_body/2`) and allow user to issue another read afterwards.
